name: Check Routine Update

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:    

permissions:
  contents: write    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Setting Permissions
        run: |
          chmod +x dump.sh
          chmod +x "bin/htmlq"
          chmod +x "bin/url-parser"
          chmod +x "bin/xidel"
        shell: bash
  
      - name: updating class routines (bi-sem)
        run: ./dump.sh "update-bi"
        shell: bash

      - name: updating term exam routines
        run: ./dump.sh "update-term"
        shell: bash      

      - name: updating supplementary exam routines
        run: ./dump.sh "update-suppli"
        shell: bash      

      - name: Commit changes
        run: ./dump.sh "push"
        shell: bash
